
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 40
#define YY_END_OF_BUFFER 41
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[286] =
    {   0,
        0,    0,   41,   40,    1,   36,   40,   40,   38,   31,
       31,   31,   31,   31,   40,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,    1,    0,    0,   30,   38,
       39,    0,    0,   38,    0,    0,    0,    0,    0,    0,
       31,   31,   31,   31,   31,   31,   31,   31,    0,    0,
       30,   31,   31,   31,   31,   31,   31,   31,   13,   31,
       31,   31,   14,   31,   31,   31,   31,   31,   31,   31,
       31,   31,    0,   29,   30,    0,    0,   33,    0,    0,
       33,    0,    0,   34,    0,    0,   33,    0,    0,   33,

        0,    0,   34,    0,    0,   35,    0,    0,   37,   37,
       31,   31,   31,   31,   31,   31,   31,   31,    0,    0,
       29,   29,   29,   31,   19,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       28,   29,   33,   33,   33,   33,   34,   34,   33,   33,
       33,   33,   34,   34,   35,   35,   37,   37,    0,   37,
       31,   31,   31,   31,   31,   31,   31,   32,   29,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   37,   37,   37,    0,   37,
       31,   31,   31,   31,    4,    2,   29,   31,    5,   31,

       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   23,   37,   37,   31,   31,   31,   31,   31,
       31,    9,   31,   31,   31,   31,   22,   31,   31,    6,
       21,   31,   31,   27,   37,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,    3,
       31,    8,   31,    7,   26,   24,   31,   15,   10,   31,
       31,   18,   31,   31,   31,   31,   31,   16,   31,   31,
       31,   20,   31,   31,   31,   31,   31,   31,   31,   31,
       25,   17,   12,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    1,    6,    7,    1,    8,    8,    8,
        9,    8,    8,    8,    8,    8,   10,    1,    1,    1,
        1,    1,    1,    1,   11,   12,   13,   11,   14,   15,
       11,   11,   16,   11,   11,   11,   17,   18,   11,   11,
       19,   11,   11,   20,   11,   11,   11,   11,   11,   21,
        1,    1,    1,    1,   22,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   11,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       11,   46,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[47] =
    {   0,
        1,    1,    1,    2,    3,    4,    5,    6,    6,    6,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    8,    7,    7,    7,    9,    7,    7,    7,
        8,    7,    7,   10,   11,   11,    7,    7,    7,   12,
        7,    7,    7,    7,    7,   13
    } ;

static const flex_int16_t yy_base[295] =
    {   0,
        0,    0,  858,  967,   45,   44,   47,   50,   58,   98,
      134,   42,  834,   40,  811,  170,  832,  831,   41,   48,
       49,   68,   95,  104,   59,  110,  811,  829,   74,   61,
      140,  116,  828,  827,  160,   48,  119,  126,  176,  179,
      182,  189,  203,    0,  209,  215,  221,  227,  233,  239,
        0,  826,  246,  282,   86,   55,   71,  825,  837,  252,
      194,  258,  270,  108,  116,  137,  117,  159,  816,  140,
      229,  199,  815,   87,  149,  271,  241,  260,  277,  210,
      176,  253,  293,  302,  305,  308,  314,  317,  320,  323,
      330,  327,  333,  336,  339,  342,  346,  350,  359,  363,

      366,  369,  372,  375,  378,  381,  384,  387,  393,  400,
      406,  813,  812,  142,  284,  393,  394,  395,    0,  413,
      425,  435,  428,  129,  811,  811,  400,   51,  295,  235,
      430,  275,  424,  248,  427,  428,  424,  434,  338,  431,
      809,  454,  460,  463,  466,  469,  472,  475,  478,  481,
      484,  487,  490,  493,  496,  499,  505,  515,  508,  522,
      528,  534,  434,  521,  522,  523,  524,    0,  560,  432,
      526,  529,  531,  570,  525,  534,  534,  558,  547,  808,
      561,  570,  570,  568,  563,  601,  611,  590,  593,  621,
      631,  588,  627,  628,  807,  806,  648,  618,  805,  608,

      636,  659,  636,  591,  646,  599,  647,  653,  655,  649,
      656,  657,  804,  692,  702,  659,  658,  661,  664,  671,
      680,  803,  610,  717,  691,  803,  801,  704,  670,  800,
      799,  694,  694,  772,  757,  695,  696,  706,  711,  712,
      713,  716,  767,  718,  721,  720,  727,  723,  728,  770,
      724,  763,  734,  736,  637,  600,  804,  573,  549,  660,
      754,  536,  755,  756,  758,  836,  759,  502,  760,  731,
      766,  795,  782,  746,  773,  774,  783,  769,  793,  794,
      404,  380,  204,  106,  967,  870,  882,  893,  901,  913,
      925,  936,  946,  953

    } ;

static const flex_int16_t yy_def[295] =
    {   0,
      285,    1,  285,  285,  285,  286,  285,  285,  285,  287,
      287,   11,   11,   11,  285,   11,   11,   11,   11,   11,
       11,   11,   16,   16,   11,   11,   16,   11,   11,   11,
       11,   11,   11,   11,   11,  285,  285,  285,  285,    9,
        9,  285,  285,    9,  285,  285,  285,  285,  285,  288,
      289,   11,  290,  290,   54,   54,   54,   11,  285,  288,
      289,   54,   11,   54,   54,   11,   54,   11,   11,   54,
       54,   11,   11,   54,   11,   54,   54,   11,   11,   54,
       54,   54,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  291,  285,  285,  292,  285,  285,  291,

      285,  285,   91,  285,  285,  292,  285,  285,  288,  288,
      293,   54,   54,   54,   54,   54,   54,   54,  294,  285,
      288,  293,  289,   54,   54,   11,   54,   11,   54,   54,
       11,   54,   54,   54,   54,   54,   11,   11,   54,   54,
       54,  285,  285,  285,   91,   91,  291,  291,  292,  292,
      291,  291,   91,   91,  292,  292,  288,  288,  285,  288,
      293,  293,   54,   54,   54,   54,   54,  294,  288,   54,
       54,   54,   11,  293,   54,   11,   54,   54,   54,   54,
       54,   11,   54,   54,   54,  288,  288,  288,  285,  288,
      293,   54,   54,   54,   54,   54,  288,   54,   54,   54,

       11,  293,   54,   11,   54,   54,   54,   54,   54,   11,
       54,   54,   54,  288,  288,   54,   54,   54,   54,   54,
       54,   54,   54,  293,   54,   11,   54,   54,   54,   54,
       54,   11,   54,   54,  288,   54,   54,   54,   54,   54,
       54,   54,  293,   54,   54,   54,   54,   11,   54,   54,
       54,   54,   54,   54,   54,   54,  293,   54,   54,   54,
       54,   11,   54,   54,   54,  293,   54,   54,   54,   54,
       54,  293,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,    0,  285,  285,  285,  285,  285,
      285,  285,  285,  285

    } ;

static const flex_int16_t yy_nxt[1014] =
    {   0,
        4,    5,    5,    6,    7,    8,    4,    9,    9,    9,
       10,   10,   10,   10,   11,   10,   12,   13,   10,   14,
       10,   15,   16,   10,   17,   10,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   10,   10,   35,   36,   36,   38,   36,
       36,   39,   39,   39,   40,   40,   40,   41,   41,   41,
       42,   43,   53,   65,   55,   44,   44,   44,   56,   58,
       53,   53,   38,   53,   67,   61,   61,   61,  113,   68,
       45,   53,   66,   53,   46,   71,  173,   76,   47,  116,
       53,   48,   49,   49,  113,  117,   53,   43,   69,  285,

       42,   50,   51,   51,   51,   51,   51,   51,  285,  113,
      113,   51,   51,   51,   38,   75,  115,   61,   61,   61,
       53,   53,   53,   83,   53,  132,   84,   84,   84,  113,
       70,  113,   53,   85,   85,   85,   53,   50,   53,  113,
      113,   51,   51,   51,   38,   72,   78,   61,   61,   61,
      127,   79,  113,  124,   80,  170,   54,   53,   53,   53,
       53,  125,   53,  113,   38,  113,   77,   61,   61,   61,
      129,   53,   53,   60,   38,  133,  126,   61,   61,   61,
      163,   53,   53,   39,   39,   39,   40,   40,   40,   41,
       41,   41,   62,   86,   87,  128,   88,   88,   88,  113,

       63,   61,   61,   61,   63,   63,  140,   89,   90,   63,
       91,   91,   91,   92,   93,   63,   94,   94,   94,   95,
       96,   53,   97,   97,   97,   98,   99,  113,  100,  100,
      100,  101,  102,  113,  103,  103,  103,  104,  105,  131,
      106,  106,  106,  107,  108,  139,  109,  109,  109,   50,
      107,  108,  113,  111,  111,  111,  120,  108,  113,  121,
      121,  121,  120,  130,  113,  122,  122,  122,  113,  113,
      113,  113,  113,  136,   83,  175,  113,  123,  123,  123,
      179,  113,   53,  141,  113,   50,  107,  108,  138,  111,
      111,  111,   53,  134,  113,  135,  137,  177,  113,   53,

      142,  142,  142,  174,  113,  114,  113,  113,  113,   84,
       84,   84,   85,   85,   85,  143,  143,  143,  113,  164,
      113,  144,  144,  144,   88,   88,   88,  145,  145,  145,
      146,  146,  146,   48,  147,  147,  147,   91,   91,   91,
      148,  148,  148,   94,   94,   94,  149,  149,  149,  150,
      150,  150,   45,   97,   97,   97,   49,  151,  151,  151,
       45,  113,  184,   48,   49,   49,  152,  152,  152,   48,
      100,  100,  100,  153,  153,  153,  154,  154,  154,  103,
      103,  103,  155,  155,  155,  156,  156,  156,  106,  106,
      106,  157,  157,  157,  158,  158,  158,  107,  108,  159,

      109,  109,  109,  113,  107,  108,  160,  109,  109,  109,
      107,  108,  159,  111,  111,  111,  113,  113,  113,  162,
      169,  169,  169,  113,  166,  167,  172,  113,  165,  107,
      108,  159,  121,  121,  121,  123,  123,  123,  160,  107,
      108,  159,  122,  122,  122,  176,   53,  113,  162,  178,
      113,  113,   53,  180,  113,  113,   53,  113,  181,  182,
      183,  142,  142,  142,  192,  198,  185,  143,  143,  143,
      144,  144,  144,  145,  145,  145,  146,  146,  146,  147,
      147,  147,  148,  148,  148,  149,  149,  149,  150,  150,
      150,  151,  151,  151,  152,  152,  152,  153,  153,  153,

      154,  154,  154,  155,  155,  155,  156,  156,  156,  107,
      108,  159,  186,  186,  186,  188,  188,  188,  160,  107,
      108,  159,  187,  187,  187,  113,  189,  108,  160,  190,
      190,  190,  107,  108,  285,  111,  111,  111,  189,  108,
      285,  191,  191,  191,  113,  113,  113,  113,  113,  113,
      195,  200,  113,   53,  205,  203,   53,  113,   53,  193,
      194,  199,  204,  196,  107,  108,  159,  197,  197,  197,
      113,  201,  113,  160,  107,  108,  159,  111,  111,  111,
      207,  113,  211,  162,  113,  210,  113,  202,  206,  209,
      212,  113,   53,  113,  107,  108,  113,  214,  214,  214,

      215,  215,  215,  160,  213,  107,  108,  159,  186,  186,
      186,  113,  216,   53,  160,  107,  108,  159,  187,  187,
      187,  228,  113,  113,  160,  107,  108,  159,  190,  190,
      190,  113,  226,  113,  160,  107,  108,  159,  191,  191,
      191,  113,  217,  219,  162,  218,  220,  222,  221,  242,
      113,  113,  107,  108,  159,  197,  197,  197,   53,  113,
      113,  160,  223,  107,  108,  285,  111,  111,  111,  113,
      113,   53,  227,  229,  225,  230,  113,  231,  113,  113,
      113,  113,  113,  113,  113,  224,  237,  113,  232,  236,
      267,  233,  239,  113,  113,  234,  107,  108,  159,  214,

      214,  214,  238,  113,  247,  160,  107,  108,  159,  235,
      235,  235,  240,  244,  113,  160,   53,  113,  113,  113,
      241,  107,  108,  285,  111,  111,  111,  113,  249,  113,
      250,  246,  252,  248,  113,  113,  113,  251,  254,  113,
      258,  113,  256,  113,  113,   53,  264,  113,  255,  275,
      113,  113,  253,  259,  113,  260,  265,  113,  262,  113,
      243,  107,  108,  159,  235,  235,  235,  261,  263,  113,
      160,  107,  108,  285,  111,  111,  111,  113,  113,  113,
      268,  113,  113,  113,  276,  269,  113,  278,  270,  113,
      271,  282,  113,  113,  274,  113,  113,  113,  273,  107,

      108,  285,  111,  111,  111,  113,  113,  257,  107,  108,
      285,  111,  111,  111,  279,  280,  113,  113,  281,  283,
      284,  277,  113,  113,  113,  245,  113,  113,  113,  113,
      113,  208,  113,  171,  113,  113,  113,   53,   53,  266,
      107,  108,  285,  111,  111,  111,  119,  118,   53,   82,
       81,   74,   73,   53,   64,   59,   57,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      272,   37,   37,  285,  285,   37,  285,   37,  285,  285,
       37,   37,   37,   52,  285,  285,  285,   52,   52,   52,
       52,   52,   52,   52,   52,  110,  110,  285,  110,  110,

      110,  110,  110,  110,  110,  110,   51,   51,   51,   51,
       51,   51,   51,   51,  112,  112,  112,  285,  112,  112,
      112,  112,  112,  112,  112,  112,   45,  285,  285,  285,
       45,  285,   45,  285,   45,  285,   45,   49,  285,  285,
      285,   49,  285,  285,   49,   49,   49,   49,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  168,
      168,  168,  168,  168,  168,  168,    3,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285
    } ;

static const flex_int16_t yy_chk[1014] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    6,   36,
       36,    6,    6,    6,    7,    7,    7,    8,    8,    8,
        9,    9,   14,   19,   12,    9,    9,    9,   12,   14,
       20,   21,   22,  128,   20,   22,   22,   22,   56,   21,
        9,   25,   19,   30,    9,   25,  128,   30,    9,   56,
       22,    9,    9,    9,   57,   57,   29,    9,   22,   23,

        9,   10,   23,   23,   23,   10,   10,   10,   24,   55,
       74,   24,   24,   24,   26,   29,   55,   26,   26,   26,
       10,   10,   10,   37,   10,   74,   37,   37,   37,  284,
       24,   64,   26,   38,   38,   38,   10,   11,   32,   65,
       67,   11,   11,   11,   31,   26,   32,   31,   31,   31,
       67,   32,  124,   64,   32,  124,   11,   11,   11,   66,
       11,   65,   31,   70,   35,  114,   31,   35,   35,   35,
       70,   75,   11,   16,   16,   75,   66,   16,   16,   16,
      114,   68,   35,   39,   39,   39,   40,   40,   40,   41,
       41,   41,   16,   42,   42,   68,   42,   42,   42,   81,

       16,   61,   61,   61,   16,   16,   81,   43,   43,   16,
       43,   43,   43,   45,   45,   16,   45,   45,   45,   46,
       46,   72,   46,   46,   46,   47,   47,  283,   47,   47,
       47,   48,   48,   80,   48,   48,   48,   49,   49,   72,
       49,   49,   49,   50,   50,   80,   50,   50,   50,   53,
       53,   53,   71,   53,   53,   53,   60,   60,  130,   60,
       60,   60,   62,   71,   77,   62,   62,   62,   53,   53,
       53,  134,   53,   77,   63,  130,   82,   63,   63,   63,
      134,   62,   78,   82,   53,   54,   54,   54,   79,   54,
       54,   54,   63,   76,   76,   76,   78,  132,  132,   79,

       83,   83,   83,  129,   54,   54,   54,  115,   54,   84,
       84,   84,   85,   85,   85,   86,   86,   86,  129,  115,
       54,   87,   87,   87,   88,   88,   88,   89,   89,   89,
       90,   90,   90,   91,   92,   92,   92,   91,   91,   91,
       93,   93,   93,   94,   94,   94,   95,   95,   95,   96,
       96,   96,   91,   97,   97,   97,   91,   98,   98,   98,
       91,  139,  139,   91,   91,   91,   99,   99,   99,   91,
      100,  100,  100,  101,  101,  101,  102,  102,  102,  103,
      103,  103,  104,  104,  104,  105,  105,  105,  106,  106,
      106,  107,  107,  107,  108,  108,  108,  109,  109,  109,

      109,  109,  109,  282,  110,  110,  109,  110,  110,  110,
      111,  111,  111,  111,  111,  111,  116,  117,  118,  111,
      120,  120,  120,  127,  117,  118,  127,  281,  116,  121,
      121,  121,  121,  121,  121,  123,  123,  123,  121,  122,
      122,  122,  122,  122,  122,  131,  137,  133,  122,  133,
      135,  136,  131,  135,  140,  170,  138,  163,  136,  137,
      138,  142,  142,  142,  163,  170,  140,  143,  143,  143,
      144,  144,  144,  145,  145,  145,  146,  146,  146,  147,
      147,  147,  148,  148,  148,  149,  149,  149,  150,  150,
      150,  151,  151,  151,  152,  152,  152,  153,  153,  153,

      154,  154,  154,  155,  155,  155,  156,  156,  156,  157,
      157,  157,  157,  157,  157,  159,  159,  159,  157,  158,
      158,  158,  158,  158,  158,  268,  160,  160,  158,  160,
      160,  160,  161,  161,  161,  161,  161,  161,  162,  162,
      162,  162,  162,  162,  164,  165,  166,  167,  175,  171,
      166,  172,  172,  173,  177,  175,  176,  177,  262,  164,
      165,  171,  176,  167,  169,  169,  169,  169,  169,  169,
      179,  173,  259,  169,  174,  174,  174,  174,  174,  174,
      179,  178,  183,  174,  181,  182,  185,  174,  178,  181,
      184,  184,  182,  183,  188,  188,  258,  188,  188,  188,

      189,  189,  189,  188,  185,  186,  186,  186,  186,  186,
      186,  192,  192,  204,  186,  187,  187,  187,  187,  187,
      187,  206,  206,  256,  187,  190,  190,  190,  190,  190,
      190,  200,  204,  223,  190,  191,  191,  191,  191,  191,
      191,  198,  193,  194,  191,  193,  194,  200,  198,  223,
      193,  194,  197,  197,  197,  197,  197,  197,  201,  203,
      255,  197,  201,  202,  202,  202,  202,  202,  202,  205,
      207,  210,  205,  207,  203,  208,  208,  209,  209,  211,
      212,  217,  216,  260,  218,  202,  217,  219,  210,  216,
      260,  211,  219,  229,  220,  212,  214,  214,  214,  214,

      214,  214,  218,  221,  229,  214,  215,  215,  215,  215,
      215,  215,  220,  225,  225,  215,  232,  233,  236,  237,
      221,  224,  224,  224,  224,  224,  224,  228,  233,  238,
      236,  228,  238,  232,  239,  240,  241,  237,  240,  242,
      244,  244,  242,  246,  245,  248,  251,  251,  241,  270,
      247,  249,  239,  245,  270,  246,  253,  253,  248,  254,
      224,  235,  235,  235,  235,  235,  235,  247,  249,  274,
      235,  243,  243,  243,  243,  243,  243,  261,  263,  264,
      261,  265,  267,  269,  271,  263,  252,  274,  264,  271,
      265,  278,  278,  250,  269,  234,  275,  276,  267,  272,

      272,  272,  272,  272,  272,  273,  277,  243,  257,  257,
      257,  257,  257,  257,  275,  276,  279,  280,  277,  279,
      280,  273,  231,  230,  227,  226,  222,  213,  199,  196,
      195,  180,  141,  126,  125,  113,  112,   73,   69,  257,
      266,  266,  266,  266,  266,  266,   59,   58,   52,   34,
       33,   28,   27,   18,   17,   15,   13,    3,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      266,  286,  286,    0,    0,  286,    0,  286,    0,    0,
      286,  286,  286,  287,    0,    0,    0,  287,  287,  287,
      287,  287,  287,  287,  287,  288,  288,    0,  288,  288,

      288,  288,  288,  288,  288,  288,  289,  289,  289,  289,
      289,  289,  289,  289,  290,  290,  290,    0,  290,  290,
      290,  290,  290,  290,  290,  290,  291,    0,    0,    0,
      291,    0,  291,    0,  291,    0,  291,  292,    0,    0,
        0,  292,    0,    0,  292,  292,  292,  292,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  294,
      294,  294,  294,  294,  294,  294,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
  #include <stdio.h>
#line 766 "lex.yy.c"
/* This tells flex to read only one input file */
/*regras*/
#line 769 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 49 "lex.l"

#line 988 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 286 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 967 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 50 "lex.l"
{/*nenhuma acao e nehum retorno*/}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "lex.l"
{printf("Foi encontrado um tipo float. Lexema: %s\n",yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 "lex.l"
{printf("Foi encontrado tipo double. Lexema: %s\n",yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "lex.l"
printf("Foi encontrado um tipo char. Lexema: %s\n",yytext);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "lex.l"
printf("Foi encontrado uma struct. Lexema: %s\n",yytext);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "lex.l"
{printf("Foi encontrado uma atribuicao '='. Lexema: %s\n",yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "lex.l"
{printf("Foi encontrado um sinal '<'. Lexema: %s\n",yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "lex.l"
{printf("Foi encontrado um sinal '>'. Lexema: %s\n",yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "lex.l"
{printf("Foi encontrado um sinal '=='. Lexema: %s\n",yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "lex.l"
{printf("Foi encontrado um sinal '!='. Lexema: %s\n",yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "lex.l"
{printf("Foi encontrado um sinal '<='. Lexema: %s\n",yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "lex.l"
{printf("Foi encontrado um sinal '>='. Lexema: %s\n",yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "lex.l"
{printf("Foi encontrado um sinal '&&'. Lexema: %s\n",yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "lex.l"
{printf("Foi encontrado um sinal '||'. Lexema: %s\n",yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "lex.l"
{printf("Foi encontrado um 'False'. Lexema: %s\n",yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "lex.l"
{printf("Foi encontrado um 'True'. Lexema: %s\n",yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "lex.l"
{printf("Foi encontrado um 'continue'. Lexema: %s\n",yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "lex.l"
{printf("Foi encontrado um 'typedef'. Lexema: %s\n",yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "lex.l"
{printf("Foi encontrado um 'do'. Lexema: %s\n",yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "lex.l"
{printf("Foi encontrado um return. Lexema: %s\n",yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "lex.l"
{printf("Foi encontrado um print. Lexema: %s\n", yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "lex.l"
{printf("Foi encontrado um for. Lexema: %s\n", yytext);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 76 "lex.l"
{printf("Foi encontrado um while. Lexema: %s\n", yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "lex.l"
{printf("Foi encontrado um if. Lexema: %s\n", yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 78 "lex.l"
{printf("Foi encontrado um else. Lexema: %s\n", yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "lex.l"
{printf("Foi encontrado um case. Lexema: %s\n", yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 80 "lex.l"
{printf("Foi encontrado um switch. Lexema: %s\n", yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "lex.l"
{printf("Foi encontrado um goto. Lexema: %s\n", yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "lex.l"
{printf("Foi encontrado um malloc. Lexema: %s\n", yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "lex.l"
{printf("Foi encontrado um sizeof. Lexema: %s\n", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "lex.l"
{printf("Foi encontrado um id. Lexema: %s\n", yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "lex.l"
{printf("Foi encontrado um ponteiro. Lexema: %s\n", yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "lex.l"
{printf("Foi encontrado uma multiplicacao. Lexema: %s\n", yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "lex.l"
{printf("Foi encontrado uma soma. Lexema: %s\n", yytext);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "lex.l"
{printf("Foi encontrado uma subtração. Lexema: %s\n", yytext);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "lex.l"
{printf("Foi encontrado um break. Lexema: %s\n", yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 "lex.l"
{printf("Foi encontrado uma atribuição. Lexema: %s\n", yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 "lex.l"
{printf("Foi encontrado um inteiro positivo. Lexema: %s\n", yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 93 "lex.l"
{printf("Foi encontrado um inteiro negativo. Lexema: %s\n", yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 95 "lex.l"
ECHO;
	YY_BREAK
#line 1246 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 286 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 286 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 285);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 95 "lex.l"


int main(void) {
    yylex();
    return 0;
}

